### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by emilianobilli** [cryptospaceship/Website#3]
Para el footer necesitaria sacar el logo de twitter y agregar el logo de Medium y discord. Intente hacerlo pero no hay caso, me quedan mas chicos o mal.

Si queres hacelo en una de las paginas y yo luego lo pongo en todas las demas.

**Comment by macarenairiarte** [comment]
Sumado en el ultimo commit!

**Comment by nicolaspajoni** [comment]
OK!
