### ISSUE TITLE
fleet.html

### ISSUE THREAD

**Issue by emilianobilli** [cryptospaceship/Website#4]
En la pagina fleet.html no quedo bien cuadrada la capa de canvas para aplicarle color. Te adjunto una captura de patalla para que lo veas. 

Debería estar superpuesta a la imagen

![image](https://user-images.githubusercontent.com/12865333/47021445-df043e00-d131-11e8-993e-328e5c82951d.png)

Ademas queda siempre seleccionado cuando uno hace click. Fijate el boton de deslizar la nave a la derecha:

![image](https://user-images.githubusercontent.com/12865333/47027046-12989580-d13d-11e8-870d-5f9b190304ff.png)

**Comment by macarenairiarte** [comment]
Emiliano! Ya está arreglado este bug! Avisame cualquier cosa!

**Comment by nicolaspajoni** [comment]
Está OK
